repos:

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/timothycrosley/isort
    rev: '5.6.4'
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
      - id: mypy
        exclude: docs/.*|tests/.*|noxfile.py
      - id: mypy
        name: mypy (Python 2)
        additional_dependencies: ["pathlib2"]
        exclude: docs/.*|tests/.*|tools/.*|noxfile.py
        args: ["-2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
      - id: check-builtin-literals
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pydocstyle.git
    rev: '5.1.1'
    hooks:
      - id: pydocstyle
        files: src/.*\.py$

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
